kind: pipeline
type: docker
name: CI_pipeline

trigger:
  event:
    - push
  branch:
    - 56-CI

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk:9.0
    commands:
      - cd src/
      - cd Memory/
      - dotnet workload restore
      - dotnet restore Memory.sln
      - dotnet build Memory.sln -c Release --no-restore
    #- dotnet publish Memory.sln -c Release --no-restore -o $CI_PROJECT_DIR/build/release
  - name: tests
    image: mcr.microsoft.com/dotnet/sdk:9.0
    commands:
      - cd src/
      - cd Memory/
      - dotnet workload restore
      - dotnet restore Memory.sln
      - dotnet test Memory.sln --no-restore
    depends_on: [build]

  - name: code-analysis
    image: hub.codefirst.iut.uca.fr/marc.chevaldonne/codefirst-dronesonarplugin-dotnet9
    secrets: [SECRET_SONAR_LOGIN]
    environment: 
      sonar_host: https://codefirst.iut.uca.fr/sonar/
      sonar_token:
        from_secrets: SECRET_SONAR_LOGIN
      project_key: SAE_1A_G7_JABBOUR_HALILOU_PERRIER_Memory
    commands: 
      - cd src/
      - dotnet workload restore
      - dotnet restore Memory.sln
      - dotnet sonarscanner begin /k:$project_key /d:sonar.host.url=$sonar_host /d:sonar.login=$sonar_token /d:sonar.verbose=true
      - dotnet build Memory.sln -c Release --no-restore
      - dotnet test Memory.sln -c Release --no-restore
     #- dotnet publish Memory.sln -c Release --no-restore -o $CI_PROJECT_DIR/build/release
      - dotnet sonarscanner end /d:sonar.login=$${sonar_token}
    depends_on: [build,tests]
